[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cookbook_manager"
version = "0.1.0"
dependencies = [
    "pydantic>=2.11.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.3",
]
